// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm4y9upG74YdXRo1hgVxFxZMLZdsmc9E0',
    appId: '1:599552293687:web:700b2e9481db209e05b8b2',
    messagingSenderId: '599552293687',
    projectId: 'fashionhind-e8cfb',
    authDomain: 'kidslearning-gohil.firebaseapp.com',
    storageBucket: 'fashionhind-e8cfb.appspot.com',
    measurementId: 'G-35MB71TXP7', //TODO change all these
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm4y9upG74YdXRo1hgVxFxZMLZdsmc9E0',
    appId: '1:118364698069:android:148aa979651e61d9de395c',
    messagingSenderId: '118364698069',
    projectId: 'fashionhind-e8cfb',
    storageBucket: 'fashionhind-e8cfb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWXJMuIbhjs_N1CPyv1Vteqi5FfSxjntw',
    appId: '1:737092768793:ios:e1ada339b7ea644cdac688',
    messagingSenderId: '737092768793',
    projectId: 'fashionhind-ios',
    storageBucket: 'fashionhind-ios.appspot.com',
    iosClientId:
        '737092768793-bu9bgqb8hoi5to9jru5rg0n5et5g5ok9.apps.googleusercontent.com',
    iosBundleId: 'com.cubixquirrel.fashionhind',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWXJMuIbhjs_N1CPyv1Vteqi5FfSxjntw',
    appId: '1:737092768793:ios:e1ada339b7ea644cdac688',
    messagingSenderId: '737092768793',
    projectId: 'fashionhind-ios',
    storageBucket: 'fashionhind-ios.appspot.com',
    iosClientId:
        '737092768793-bu9bgqb8hoi5to9jru5rg0n5et5g5ok9.apps.googleusercontent.com',
    iosBundleId: 'com.cubixquirrel.fashionhind.RunnerTests',
  );//TODO change all these
}
